#!/usr/bin/env python3
"""
LVOmniBench subset evaluation script.

Take a specified number of questions from lvomnibench.json, generate a subset JSON,
then call lv_harness for offline evaluation (using pre-built memory).

Usage:
    # Default: first 128 questions
    python run_homer.py

    # Custom parameters
    python run_homer.py \
        --num_questions 128 \
        --model gemini-2.5-flash \
        --workers 4 \
        --output_dir data/results/lvomnibench_test
"""
import os
import sys
import json
import argparse
import logging
import time
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
)
logger = logging.getLogger(__name__)

# ============================================================
# Path constants (can be overridden via command-line arguments)
# ============================================================
# Path prefix: prefer the full path, fall back to the short path
_PREFIX = "/path/to"
_PREFIX_CQ11 = "/path/to"

DEFAULT_ANNOTATION_FILE = f"{_PREFIX}/lv_harness/data/annotations/lvomnibench.json"
DEFAULT_EVENTGRAPH_DIR = f"{_PREFIX_CQ11}/data/LVOmniBench/videos/event_graphs/refined"
DEFAULT_API_CONFIG = f"{_PREFIX}/lv_harness/configs/api_config.json"
DEFAULT_MEMORY_CONFIG = f"{_PREFIX}/lv_harness/configs/memory_config.json"


def parse_args():
    parser = argparse.ArgumentParser(
        description="LVOmniBench subset evaluation: take the first N questions and evaluate using offline memory"
    )
    # Data parameters
    parser.add_argument("--annotation_file", type=str, default=DEFAULT_ANNOTATION_FILE,
                        help="Path to the full lvomnibench.json")
    parser.add_argument("--num_questions", type=int, default=128,
                        help="Number of questions to take (default 128)")
    parser.add_argument("--subset_output", type=str, default=None,
                        help="Output path for the subset JSON (auto-generated by default)")

    # Memory parameters
    parser.add_argument("--eventgraph_dir", type=str, default=DEFAULT_EVENTGRAPH_DIR,
                        help="EventGraph data directory")
    parser.add_argument("--memory_config", type=str, default=DEFAULT_MEMORY_CONFIG,
                        help="Path to memory_config.json")
    parser.add_argument("--strategy", type=str, default="hierarchical",
                        choices=["hierarchical", "no_graph_walk", "videograph_only",
                                 "eventgraph_only", "sliding_window", "compressed"],
                        help="Memory strategy (default hierarchical)")

    # Reasoning parameters
    parser.add_argument("--agent", type=str, default="ledger_multi_round",
                        choices=["multi_round_search", "ledger_multi_round"],
                        help="Reasoning agent type; ledger_multi_round enables TaskLedger-driven multi-round retrieval.")
    parser.add_argument("--ledger_max_subtasks", type=int, default=5,
                        help="Only effective for --agent ledger_multi_round: max number of subtasks from the Planner")
    parser.add_argument("--ledger_max_attempts", type=int, default=3,
                        help="Only effective for --agent ledger_multi_round: max retry count per subtask")
    parser.add_argument("--ledger_synthesis_raw", action="store_true",
                        help="Only effective for --agent ledger_multi_round: synthesis also attaches the raw retrieval log (for debugging)")
    parser.add_argument("--model", type=str, default="gemini-2.5-flash",
                        help="Reasoning model name")
    parser.add_argument("--backend", type=str, default="openai",
                        choices=["openai", "vllm"],
                        help="Reasoning backend")
    parser.add_argument("--max_rounds", type=int, default=5,
                        help="Maximum number of reasoning rounds")
    parser.add_argument("--workers", type=int, default=4,
                        help="Concurrency level")
    parser.add_argument("--batch_size", type=int, default=64,
                        help="Batch size")
    parser.add_argument("--api_config", type=str, default=DEFAULT_API_CONFIG,
                        help="Path to the API config file")

    # Evaluation parameters
    parser.add_argument("--eval_model", type=str, default="gemini-2.5-flash",
                        help="Evaluation model name")
    parser.add_argument("--string_match_first", dest="string_match_first",
                        action="store_true", default=True,
                        help="Prefer string matching during evaluation (default, suitable for multiple-choice questions)")
    parser.add_argument("--no_string_match", dest="string_match_first",
                        action="store_false",
                        help="Disable string matching and force the eval_model to score (suitable for open-ended QA, e.g. M3-Bench)")

    # Output parameters
    parser.add_argument("--output_dir", type=str, default=None,
                        help="Output directory (auto-generated by default)")
    parser.add_argument("--save_trajectory", action="store_true",
                        help="Save the full reasoning trajectory (one JSON file per question, containing the full conversation, retrieval results, and reasoning process)")

    # Run mode
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("--streaming", action="store_true",
                            help="Enable streaming reasoning mode (watch the video, build memory, and answer questions simultaneously)")
    mode_group.add_argument("--batch_mode", action="store_true", default=True,
                            help="Use batch processing mode (default, loads pre-built memory)")

    # Streaming-only parameters
    parser.add_argument("--clip_dir_template", type=str, default=None,
                        help="Clip directory template, e.g. '/path/to/clips/{video_name}' (required in streaming mode)")
    parser.add_argument("--eventgraph_incremental", action="store_true",
                        help="Enable EventGraph incremental updates (only effective in streaming mode)")
    parser.add_argument("--eventgraph_update_interval", type=int, default=20,
                        help="EventGraph incremental update interval (number of clips, default 20)")
    parser.add_argument("--eventgraph_model", type=str, default="DeepSeek-V3.1T",
                        help="LLM model used for EventGraph incremental updates")
    parser.add_argument("--memory_cache_dir", type=str, default="",
                        help="Memory cache directory in streaming mode (empty means no caching; once set, the same video can reuse the already-built memory)")

    # Self-evolution parameters
    parser.add_argument("--evolution", action="store_true",
                        help="Enable the self-evolution system (experience capture, skill distillation, skill injection, wisdom distillation)")
    parser.add_argument("--evolution_dir", type=str, default="",
                        help="Root directory for self-evolution data storage (empty means use output_dir/.lv_harness)")
    parser.add_argument("--load_prior_skills", action="store_true",
                        help="Whether to load historical skills from evolution_dir/skills at startup (not loaded by default, to facilitate controlled experiments)")
    parser.add_argument("--load_prior_learnings", action="store_true",
                        help="Whether to load historical structured experiences from evolution_dir/learnings/learnings.jsonl at startup, used for the Planner decomposition decisions (not loaded by default)")
    parser.add_argument("--promote_threshold", type=int, default=3,
                        help="Trigger skill promotion when N experiences of the same kind are accumulated (default 3)")
    parser.add_argument("--route_threshold", type=float, default=0.3,
                        help="Skill routing match score threshold (default 0.3)")
    parser.add_argument("--wisdom_use_llm", action="store_true",
                        help="Whether the WisdomDistiller uses an LLM to produce strategy-level insights (pure statistics by default)")
    parser.add_argument("--wisdom_model", type=str, default="gemini-2.5-flash",
                        help="LLM model used by the WisdomDistiller (only effective with --wisdom_use_llm)")
    parser.add_argument("--reflection_llm_max_tokens", type=int, default=8192,
                        help="Maximum output tokens for the LLM-generated reflection (default 8192; too low may cause Markdown truncation)")
    parser.add_argument("--skill_use_llm_instructions", action="store_true",
                        help="Whether to call the LLM to generate special_instructions for each new skill (off by default; when off, a template placeholder is used)")
    parser.add_argument("--skill_instructions_llm_model", type=str, default="gemini-2.5-flash",
                        help="LLM model used to generate skill special_instructions (only effective with --skill_use_llm_instructions)")

    # Misc
    parser.add_argument("--enable_thinking", action="store_true",
                        help="Enable DeepSeek-V4 thinking mode (off by default)")

    parser.add_argument("--dry_run", action="store_true",
                        help="Only generate the subset JSON, do not run evaluation")

    # Third layer: visual layer (KEYFRAME retrieval). Off by default to ensure backward compatibility.
    parser.add_argument("--visual_layer_enabled", action="store_true",
                        help="Enable the third visual layer (the agent can explicitly emit a KEYFRAME: action)")
    parser.add_argument("--visual_clips_root", type=str, default="",
                        help="Visual layer clips root directory; keyframe path = {clips_root}/{video_name}/{keyframe_dir_name}")
    parser.add_argument("--visual_keyframe_dir_name", type=str, default="keyframe_hybridv2",
                        help="Keyframe subdirectory name (default keyframe_hybridv2)")
    parser.add_argument("--visual_max_images_per_call", type=int, default=5,
                        help="Maximum number of images returned per KEYFRAME retrieval (default 5)")

    return parser.parse_args()


def resolve_path(path: str) -> str:
    """Return the path itself (placeholder implementation; replace with actual path-resolution logic as needed)."""
    return path


def extract_subset(annotation_file: str, num_questions: int, output_path: str) -> dict:
    """Take the first N questions from the full dataset.

    Iterate in video order and stop when the accumulated question count reaches num_questions.
    If num_questions == -1, return all data.
    Preserve full video granularity (the qa_list of a video is never truncated).

    Returns:
        The subset data dictionary
    """
    logger.info(f"Loading full dataset: {annotation_file}")
    with open(annotation_file, "r", encoding="utf-8") as f:
        full_data = json.load(f)

    subset = {}
    total_questions = 0
    total_videos = 0
    path_fixed_count = 0

    # If -1, return all data directly
    if num_questions == -1:
        logger.info("num_questions=-1, using all data")
        subset = full_data
        for video_key, video_data in subset.items():
            qa_list = video_data.get("qa_list", [])
            total_questions += len(qa_list)
            total_videos += 1
            
            # Automatically fix paths
            for path_key in ("mem_path", "video_path"):
                original = video_data.get(path_key, "")
                if original:
                    resolved = resolve_path(original)
                    if resolved != original:
                        subset[video_key][path_key] = resolved
                        path_fixed_count += 1
    else:
        # Take the first N entries
        for video_key, video_data in full_data.items():
            qa_list = video_data.get("qa_list", [])
            remaining = num_questions - total_questions

            if remaining <= 0:
                break

            # Auto-fix paths
            fixed_data = dict(video_data)
            for path_key in ("mem_path", "video_path"):
                original = fixed_data.get(path_key, "")
                if original:
                    resolved = resolve_path(original)
                    if resolved != original:
                        fixed_data[path_key] = resolved
                        path_fixed_count += 1

            if len(qa_list) <= remaining:
                subset[video_key] = fixed_data
                total_questions += len(qa_list)
            else:
                subset[video_key] = {
                    **fixed_data,
                    "qa_list": qa_list[:remaining],
                }
                total_questions += remaining

            total_videos += 1

    logger.info(f"Subset stats: {total_videos} videos, {total_questions} questions")
    if path_fixed_count > 0:
        logger.info(f"Automatically fixed {path_fixed_count} path prefixes")

    # Save the subset
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(subset, f, ensure_ascii=False, indent=2)
    logger.info(f"Subset saved: {output_path}")

    return subset


def run_evaluation(args, subset_path: str):
    """Call lv_harness to run evaluation."""
    # Ensure lv_harness is in PYTHONPATH
    lv_harness_root = str(Path(__file__).resolve().parent)
    if lv_harness_root not in sys.path:
        sys.path.insert(0, lv_harness_root)

    from lv_harness.orchestrator import HarnessOrchestrator

    # Build the output directory
    n_suffix = "all" if args.num_questions == -1 else f"n{args.num_questions}"
    # Toggle tags: visual layer kfon/kfoff, self-evolution evoon/evooff
    kf_tag = "kfon" if getattr(args, "visual_layer_enabled", False) else "kfoff"
    evo_tag = "evoon" if getattr(args, "evolution", False) else "evooff"
    output_dir = args.output_dir or os.path.join(
        lv_harness_root, "data", "results",
        f"lvomnibench_{n_suffix}_{kf_tag}_{evo_tag}_{args.model}_{time.strftime('%Y%m%d_%H%M%S')}"
    )
    os.makedirs(output_dir, exist_ok=True)

    # Build the override parameters
    # Automatically fix the eventgraph_dir path
    eventgraph_dir = resolve_path(args.eventgraph_dir)
    api_config = resolve_path(args.api_config)
    memory_config = resolve_path(args.memory_config)

    # Decide temporal_mode based on the run mode
    is_streaming = getattr(args, 'streaming', False)
    temporal_mode = "periodic" if is_streaming else "end_of_video"

    # Task name: prefer deriving it from the subset_path filename, so that different datasets such as
    # m3bench/lvomnibench produce output files matching the directory name (e.g. m3bench_robot_all-<model>-lv_harness.jsonl)
    task_suffix = "all" if args.num_questions == -1 else f"subset_{args.num_questions}"
    try:
        task_name = os.path.splitext(os.path.basename(subset_path))[0] or f"lvomnibench_{task_suffix}"
    except Exception:
        task_name = f"lvomnibench_{task_suffix}"

    overrides = {
        # Data
        "task": task_name,
        "data.annotation_file": subset_path,
        "data.temporal_mode": temporal_mode,
        # Memory
        "memory.strategy": args.strategy,
        "memory.eventgraph_dir": eventgraph_dir,
        "memory.memory_config_path": memory_config,
        # Reasoning
        "reasoning.agent": getattr(args, "agent", "ledger_multi_round"),
        "reasoning.backend": args.backend,
        "reasoning.model": args.model,
        "reasoning.max_rounds": args.max_rounds,
        "reasoning.workers": args.workers,
        "reasoning.api_config_path": api_config,
        # Evaluation
        "evaluation.eval_model": args.eval_model,
        "evaluation.string_match_first": args.string_match_first,
        "evaluation.metrics": ["accuracy", "accuracy_by_category", "answer_latency"],
        # Output
        "output.dir": output_dir,
        "output.save_trajectory": getattr(args, 'save_trajectory', False),
    }

    # TaskLedger-specific parameters (injected only when agent == ledger_multi_round)
    if getattr(args, "agent", "ledger_multi_round") == "ledger_multi_round":
        overrides["reasoning.ledger.enabled"] = True
        overrides["reasoning.ledger.planner.enabled"] = True
        overrides["reasoning.ledger.planner.max_subtasks"] = int(
            getattr(args, "ledger_max_subtasks", 5)
        )
        overrides["reasoning.ledger.scheduler.max_attempts_per_subtask"] = int(
            getattr(args, "ledger_max_attempts", 3)
        )
        # By default synthesis uses only the ledger; adding --ledger_synthesis_raw also attaches the raw retrieval
        overrides["reasoning.ledger.synthesis.use_ledger_only"] = (
            not bool(getattr(args, "ledger_synthesis_raw", False))
        )

    # Streaming-mode-specific configuration
    if is_streaming:
        if args.clip_dir_template:
            overrides["data.clip_dir_template"] = args.clip_dir_template
        overrides["memory.eventgraph_incremental"] = getattr(
            args, 'eventgraph_incremental', False
        )
        overrides["memory.eventgraph_update_interval"] = getattr(
            args, 'eventgraph_update_interval', 20
        )
        overrides["memory.eventgraph_model"] = getattr(
            args, 'eventgraph_model', 'DeepSeek-V3.1T'
        )
        # Memory cache directory
        memory_cache_dir = getattr(args, 'memory_cache_dir', '')
        if memory_cache_dir:
            overrides["memory.memory_cache_dir"] = memory_cache_dir

    if args.evolution:
        overrides["evolution.enabled"] = True
        # Determine evolution_dir: prefer the user-specified one, otherwise place it under output_dir to keep each experiment isolated
        evo_dir = args.evolution_dir or os.path.join(output_dir, ".lv_harness")
        overrides["evolution.dir"] = evo_dir
        overrides["evolution.learnings_dir"] = f"{evo_dir}/learnings"
        overrides["evolution.skills_dir"] = f"{evo_dir}/skills"
        overrides["evolution.wisdom_path"] = f"{evo_dir}/WISDOM.md"
        overrides["evolution.reflections_dir"] = f"{evo_dir}/reflections"
        overrides["evolution.load_prior_skills"] = args.load_prior_skills
        overrides["evolution.load_prior_learnings"] = args.load_prior_learnings
        overrides["evolution.promote_threshold"] = args.promote_threshold
        overrides["evolution.route_threshold"] = args.route_threshold
        overrides["evolution.visual_layer_enabled"] = bool(
            getattr(args, "visual_layer_enabled", False)
        )
        overrides["evolution.wisdom_use_llm"] = args.wisdom_use_llm
        overrides["evolution.wisdom_llm_model"] = args.wisdom_model
        overrides["evolution.reflection_llm_max_tokens"] = args.reflection_llm_max_tokens
        # P1: toggle for LLM generation of Skill special_instructions
        if getattr(args, "skill_use_llm_instructions", False):
            overrides["evolution.skill_use_llm_instructions"] = True
        if getattr(args, "skill_instructions_llm_model", None):
            overrides["evolution.skill_instructions_llm_model"] = args.skill_instructions_llm_model

    # DeepSeek-V4 thinking mode toggle
    if getattr(args, "enable_thinking", False):
        overrides["reasoning.enable_thinking"] = True
        overrides["evaluation.enable_thinking"] = True

    # Third layer: visual layer parameters (off by default. When on, project the config into memory.visual_layer.*)
    if getattr(args, "visual_layer_enabled", False):
        overrides["memory.visual_layer.enabled"] = True
        overrides["memory.visual_layer.clips_root"] = getattr(args, "visual_clips_root", "") or ""
        overrides["memory.visual_layer.keyframe_dir_name"] = getattr(
            args, "visual_keyframe_dir_name", "keyframe_hybridv2"
        )
        overrides["memory.visual_layer.max_images_per_call"] = int(
            getattr(args, "visual_max_images_per_call", 5) or 5
        )

    logger.info("=" * 60)
    logger.info("LVOmniBench subset evaluation")
    logger.info("=" * 60)
    logger.info(f"  Dataset: {subset_path}")
    logger.info(f"  Number of questions: {args.num_questions}")
    logger.info(f"  Model: {args.model}")
    logger.info(f"  Memory strategy: {args.strategy}")
    logger.info(f"  Reasoning Agent: {getattr(args, 'agent', 'multi_round_search')}")
    logger.info(f"  Run mode: {'streaming reasoning' if is_streaming else 'offline batch'}")
    logger.info(f"  EventGraph: {args.eventgraph_dir}")
    if is_streaming:
        logger.info(f"  Clip directory template: {getattr(args, 'clip_dir_template', 'N/A')}")
        logger.info(f"  EventGraph incremental update: {getattr(args, 'eventgraph_incremental', False)}")
        memory_cache_dir = getattr(args, 'memory_cache_dir', '')
        if memory_cache_dir:
            logger.info(f"  Memory cache directory: {memory_cache_dir}")
        else:
            logger.info(f"  Memory cache: not enabled")
    if args.evolution:
        evo_dir = args.evolution_dir or os.path.join(output_dir, ".lv_harness")
        logger.info(f"  Self-evolution: enabled")
        logger.info(f"    evolution_dir: {evo_dir}")
        logger.info(f"    load_prior_skills: {args.load_prior_skills}")
        logger.info(f"    load_prior_learnings: {args.load_prior_learnings}")
        logger.info(f"    promote_threshold: {args.promote_threshold}")
        logger.info(f"    route_threshold: {args.route_threshold}")
        logger.info(f"    wisdom_use_llm: {args.wisdom_use_llm}")
        logger.info(f"    skill_use_llm_instructions: {getattr(args, 'skill_use_llm_instructions', False)}")
    logger.info(f"  Max rounds: {args.max_rounds}")
    logger.info(f"  Concurrency: {args.workers}")
    logger.info(f"  string_match_first: {args.string_match_first}")
    logger.info(f"  Output directory: {output_dir}")
    logger.info("=" * 60)

    # Create the Orchestrator and run
    harness = HarnessOrchestrator(overrides=overrides)
    if is_streaming:
        results = harness.run_streaming()
    else:
        results = harness.run_batch(batch_size=args.batch_size)

    # Print the results
    logger.info("=" * 60)
    logger.info("Evaluation complete")
    logger.info("=" * 60)
    for metric, value in results.items():
        if isinstance(value, dict):
            logger.info(f"[{metric}]")
            for k, v in value.items():
                if isinstance(v, float):
                    logger.info(f"  {k}: {v:.4f}")
                else:
                    logger.info(f"  {k}: {v}")
        else:
            logger.info(f"  {metric}: {value}")

    return results


def main():
    args = parse_args()

    # Generate the subset JSON path
    if args.subset_output:
        subset_path = args.subset_output
    else:
        lv_harness_root = str(Path(__file__).resolve().parent)
        subset_dir = os.path.join(lv_harness_root, "data", "annotations")
        os.makedirs(subset_dir, exist_ok=True)
        file_suffix = "all" if args.num_questions == -1 else f"subset_{args.num_questions}"
        subset_path = os.path.join(subset_dir, f"lvomnibench_{file_suffix}.json")

    # Step 1: take the subset
    if os.path.exists(subset_path):
        logger.info(f"Subset file already exists, skipping generation: {subset_path}")
        with open(subset_path, "r", encoding="utf-8") as f:
            subset = json.load(f)
        total_q = sum(len(v.get("qa_list", [])) for v in subset.values())
        logger.info(f"Existing subset: {len(subset)} videos, {total_q} questions")
    else:
        subset = extract_subset(args.annotation_file, args.num_questions, subset_path)

    if args.dry_run:
        logger.info("Dry run mode: only generate the subset JSON, do not run evaluation")
        return

    # Step 2: run evaluation
    results = run_evaluation(args, subset_path)

    return results


if __name__ == "__main__":
    main()
