#!/usr/bin/env python3
"""
LVOmniBench subset evaluation script.

Take a specified number of questions from lvomnibench.json, generate a subset JSON,
then call lv_harness for offline evaluation (using pre-built memory).

Usage:
    # Default: first 128 questions
    python run_homer_batch_evo.py

    # Custom parameters
    python run_homer_batch_evo.py \
        --num_questions 128 \
        --model gemini-2.5-flash \
        --workers 4 \
        --output_dir data/results/lvomnibench_test
"""
import os
import sys
import json
import copy
import argparse
import logging
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
)
logger = logging.getLogger(__name__)

# ============================================================
# Path constants (can be overridden via command-line arguments)
# ============================================================
# Path prefix: prefer the full path, fall back to the short path
_PREFIX = "/path/to"
_PREFIX_CQ11 = "/path/to"

DEFAULT_ANNOTATION_FILE = f"{_PREFIX}/lv_harness/data/annotations/lvomnibench.json"
DEFAULT_EVENTGRAPH_DIR = f"{_PREFIX_CQ11}/data/LVOmniBench/videos/event_graphs/refined"
DEFAULT_API_CONFIG = f"{_PREFIX}/lv_harness/configs/api_config.json"
DEFAULT_MEMORY_CONFIG = f"{_PREFIX}/lv_harness/configs/memory_config.json"


def parse_args():
    parser = argparse.ArgumentParser(
        description="LVOmniBench subset evaluation: take the first N questions and evaluate using offline memory"
    )
    # Data parameters
    parser.add_argument("--annotation_file", type=str, default=DEFAULT_ANNOTATION_FILE,
                        help="Path to the full lvomnibench.json")
    parser.add_argument("--num_questions", type=int, default=128,
                        help="Number of questions to take (default 128)")
    parser.add_argument("--question_offset", type=int, default=0,
                        help="Question offset: a positive value skips the first N questions and starts from the (N+1)-th; "
                             "a negative value counts from the end (e.g. -600 means take the last 600). Default 0 means start from the beginning")
    parser.add_argument("--subset_output", type=str, default=None,
                        help="Output path for the subset JSON (auto-generated by default)")

    # Memory parameters
    parser.add_argument("--eventgraph_dir", type=str, default=DEFAULT_EVENTGRAPH_DIR,
                        help="EventGraph data directory")
    parser.add_argument("--memory_config", type=str, default=DEFAULT_MEMORY_CONFIG,
                        help="Path to memory_config.json")
    parser.add_argument("--strategy", type=str, default="hierarchical",
                        choices=["hierarchical", "no_graph_walk", "videograph_only",
                                 "eventgraph_only", "sliding_window", "compressed"],
                        help="Memory strategy (default hierarchical)")

    # Reasoning parameters
    parser.add_argument("--agent", type=str, default="ledger_multi_round",
                        choices=["multi_round_search", "ledger_multi_round", "decompose_only", "control_api_harness"],
                        help="Reasoning agent type; "
                             "ledger_multi_round enables TaskLedger-driven multi-round retrieval; "
                             "decompose_only performs task decomposition + focus scheduling only, without injecting ledger content into the context (control experiment); "
                             "control_api_harness uses the original control_api.py prompt + retrieval, with the harness machinery added.")
    parser.add_argument("--ledger_max_subtasks", type=int, default=5,
                        help="Only effective for --agent ledger_multi_round / decompose_only: max number of subtasks from the Planner")
    parser.add_argument("--ledger_max_attempts", type=int, default=3,
                        help="Only effective for --agent ledger_multi_round / decompose_only: max retries per subtask")
    parser.add_argument("--ledger_synthesis_raw", action="store_true",
                        help="Only effective for --agent ledger_multi_round: also attach raw retrieval logs to synthesis (for debugging)")
    parser.add_argument("--planner_temperature", type=float, default=0.2,
                        help="Only effective for --agent ledger_multi_round / decompose_only: LLM sampling temperature for Planner decomposition (default 0.2)")
    parser.add_argument("--model", type=str, default="gemini-2.5-flash",
                        help="Reasoning model name")
    parser.add_argument("--backend", type=str, default="openai",
                        choices=["openai", "vllm"],
                        help="Reasoning backend")
    parser.add_argument("--max_rounds", type=int, default=5,
                        help="Maximum number of reasoning rounds")
    parser.add_argument("--workers", type=int, default=4,
                        help="Concurrency level")
    parser.add_argument("--batch_size", type=int, default=64,
                        help="Batch size")
    parser.add_argument("--api_config", type=str, default=DEFAULT_API_CONFIG,
                        help="Path to the API config file")

    # Evaluation parameters
    parser.add_argument("--eval_model", type=str, default="gemini-2.5-flash",
                        help="Evaluation model name")
    parser.add_argument("--string_match_first", dest="string_match_first",
                        action="store_true", default=True,
                        help="Prefer string matching during evaluation (default, suitable for multiple-choice questions)")
    parser.add_argument("--no_string_match", dest="string_match_first",
                        action="store_false",
                        help="Disable string matching and force the eval_model to score (suitable for open-ended QA, e.g. M3-Bench)")

    # Output parameters
    parser.add_argument("--output_dir", type=str, default=None,
                        help="Output directory (auto-generated by default)")
    parser.add_argument("--save_trajectory", action="store_true",
                        help="Save the full reasoning trajectory (one JSON file per question, containing the full conversation, retrieval results, and reasoning process)")

    # Run mode
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("--streaming", action="store_true",
                            help="Enable streaming reasoning mode (watch the video, build memory, and answer questions simultaneously)")
    mode_group.add_argument("--batch_mode", action="store_true", default=True,
                            help="Use batch processing mode (default, loads pre-built memory)")

    # Streaming-only parameters
    parser.add_argument("--clip_dir_template", type=str, default=None,
                        help="Clip directory template, e.g. '/path/to/clips/{video_name}' (required in streaming mode)")
    parser.add_argument("--eventgraph_incremental", action="store_true",
                        help="Enable EventGraph incremental updates (only effective in streaming mode)")
    parser.add_argument("--eventgraph_update_interval", type=int, default=20,
                        help="EventGraph incremental update interval (number of clips, default 20)")
    parser.add_argument("--eventgraph_model", type=str, default="DeepSeek-V3.1T",
                        help="LLM model used for EventGraph incremental updates")
    parser.add_argument("--memory_cache_dir", type=str, default="",
                        help="Memory cache directory in streaming mode (empty means no caching; once set, the same video can reuse the already-built memory)")

    # Self-evolution parameters
    parser.add_argument("--evolution", action="store_true",
                        help="Enable the self-evolution system (experience capture, skill distillation, skill injection, wisdom distillation)")
    parser.add_argument("--evolution_dir", type=str, default="",
                        help="Root directory for self-evolution data storage (empty means use output_dir/.lv_harness)")
    parser.add_argument("--load_prior_skills", action="store_true",
                        help="Whether to load historical skills from evolution_dir/skills at startup (not loaded by default, to facilitate controlled experiments)")
    parser.add_argument("--load_prior_learnings", action="store_true",
                        help="Whether to load historical structured experiences from evolution_dir/learnings/learnings.jsonl at startup, used for the Planner decomposition decisions (not loaded by default)")
    parser.add_argument("--promote_threshold", type=int, default=3,
                        help="Trigger skill promotion when N experiences of the same kind are accumulated (default 3)")
    parser.add_argument("--route_threshold", type=float, default=0.3,
                        help="Skill routing match score threshold (default 0.3)")
    parser.add_argument("--wisdom_use_llm", action="store_true",
                        help="Whether the WisdomDistiller uses an LLM to produce strategy-level insights (pure statistics by default)")
    parser.add_argument("--wisdom_model", type=str, default="gemini-2.5-flash",
                        help="LLM model used by the WisdomDistiller (only effective with --wisdom_use_llm)")
    parser.add_argument("--reflection_llm_max_tokens", type=int, default=8192,
                        help="Maximum output tokens for the LLM-generated reflection (default 8192; too low may cause Markdown truncation)")
    parser.add_argument("--skill_use_llm_instructions", action="store_true",
                        help="Whether to call the LLM to generate special_instructions for each new skill (off by default; when off, a template placeholder is used)")
    parser.add_argument("--skill_instructions_llm_model", type=str, default="gemini-2.5-flash",
                        help="LLM model used to generate skill special_instructions (only effective with --skill_use_llm_instructions)")
    parser.add_argument("--evolution_readonly", action="store_true",
                        help="Self-evolution read-only mode: load existing skills for reasoning injection, but do not write any learning/skill/wisdom (for pure evaluation experiments)")

    # Misc
    parser.add_argument("--temperature", type=float, default=0.4,
                        help="LLM sampling temperature (shared by the reasoning agent / planner / evolution; eval is fixed at 0)")
    parser.add_argument("--seed", type=int, default=42,
                        help="LLM decoding random seed (default 42; set to -1 to not pass a seed)")
    parser.add_argument("--enable_thinking", action="store_true",
                        help="Enable DeepSeek-V4 thinking mode (off by default)")
    parser.add_argument("--no_reason", action="store_true",
                        help="Disable the Reason output mode (do not require the model to output a Reason line in the prompt; Reason is on by default)")

    parser.add_argument("--dry_run", action="store_true",
                        help="Only generate the subset JSON, do not run evaluation")

    # Third layer: visual layer (KEYFRAME retrieval). Off by default to ensure backward compatibility.
    parser.add_argument("--visual_layer_enabled", action="store_true",
                        help="Enable the third visual layer (the agent can explicitly emit a KEYFRAME: action)")
    parser.add_argument("--visual_clips_root", type=str, default="",
                        help="Visual layer clips root directory; keyframe path = {clips_root}/{video_name}/{keyframe_dir_name}")
    parser.add_argument("--visual_keyframe_dir_name", type=str, default="keyframe_hybridv2",
                        help="Keyframe subdirectory name (default keyframe_hybridv2)")
    parser.add_argument("--visual_max_images_per_call", type=int, default=5,
                        help="Maximum number of images returned per KEYFRAME retrieval (default 5)")

    return parser.parse_args()


def resolve_path(path: str) -> str:
    """Return the path itself (placeholder implementation; replace with actual path-resolution logic as needed)."""
    return path


def extract_subset(annotation_file: str, num_questions: int, output_path: str,
                   question_offset: int = 0) -> dict:
    """Take a question subset from the full dataset.

    Iterate in video order, supporting several selection modes:
      - num_questions == -1 and offset == 0: return all data
      - num_questions == -1 and offset > 0: skip the first offset questions, return the rest
      - num_questions == -1 and offset < 0: return the last |offset| questions (equivalent to offset=negative, num=-1)
      - num_questions > 0 and offset == 0: take the first N from the beginning
      - num_questions > 0 and offset > 0: skip the first offset, then take N
      - num_questions > 0 and offset < 0: take N counting from the end (offset specifies the starting position)

    When question_offset < 0, the semantics is "counting from the end":
      - offset=-600, num_questions=-1: take the last 600
      - offset=-600, num_questions=100: take 100 starting from the 600th-from-last

    Returns:
        The subset data dictionary
    """
    logger.info(f"Loading full dataset: {annotation_file}")
    with open(annotation_file, "r", encoding="utf-8") as f:
        full_data = json.load(f)

    # First count the total number of questions, used to handle a negative offset
    all_questions_count = sum(
        len(v.get("qa_list", [])) for v in full_data.values()
    )
    logger.info(f"Full dataset: {len(full_data)} videos, {all_questions_count} questions")

    # Convert a negative offset into a positive offset
    effective_offset = question_offset
    if question_offset < 0:
        effective_offset = max(0, all_questions_count + question_offset)
        logger.info(f"Negative offset {question_offset} -> start from question {effective_offset + 1}"
                    f" (skip the first {effective_offset}, take data among the last {all_questions_count - effective_offset})")

    subset = {}
    total_questions = 0
    total_videos = 0
    path_fixed_count = 0
    skipped_questions = 0  # number of questions already skipped

    # If -1 and no offset, return all data directly
    if num_questions == -1 and effective_offset == 0:
        logger.info("num_questions=-1 and offset=0, using all data")
        subset = full_data
        for video_key, video_data in subset.items():
            qa_list = video_data.get("qa_list", [])
            total_questions += len(qa_list)
            total_videos += 1

            # Automatically fix paths
            for path_key in ("mem_path", "video_path"):
                original = video_data.get(path_key, "")
                if original:
                    resolved = resolve_path(original)
                    if resolved != original:
                        subset[video_key][path_key] = resolved
                        path_fixed_count += 1
    else:
        # Determine the actual number to take
        if num_questions == -1:
            target_count = all_questions_count - effective_offset
        else:
            target_count = num_questions

        for video_key, video_data in full_data.items():
            qa_list = video_data.get("qa_list", [])

            # Phase 1: skip the offset portion
            if skipped_questions < effective_offset:
                remaining_to_skip = effective_offset - skipped_questions
                if len(qa_list) <= remaining_to_skip:
                    # The whole video is within the skip range
                    skipped_questions += len(qa_list)
                    continue
                else:
                    # Partial skip: take the latter part of this video's qa_list
                    qa_list = qa_list[remaining_to_skip:]
                    skipped_questions += remaining_to_skip

            # Phase 2: collect data
            if total_questions >= target_count:
                break

            remaining = target_count - total_questions

            # Automatically fix paths
            fixed_data = dict(video_data)
            for path_key in ("mem_path", "video_path"):
                original = fixed_data.get(path_key, "")
                if original:
                    resolved = resolve_path(original)
                    if resolved != original:
                        fixed_data[path_key] = resolved
                        path_fixed_count += 1

            if len(qa_list) <= remaining:
                subset[video_key] = {**fixed_data, "qa_list": qa_list}
                total_questions += len(qa_list)
            else:
                subset[video_key] = {
                    **fixed_data,
                    "qa_list": qa_list[:remaining],
                }
                total_questions += remaining

            total_videos += 1

    logger.info(f"Subset stats: {total_videos} videos, {total_questions} questions"
                f" (offset={question_offset}, effective_offset={effective_offset})")
    if path_fixed_count > 0:
        logger.info(f"Automatically fixed {path_fixed_count} path prefixes")

    # Save the subset
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(subset, f, ensure_ascii=False, indent=2)
    logger.info(f"Subset saved: {output_path}")

    return subset


def run_evaluation(args, subset_path: str):
    """Call lv_harness to run evaluation."""
    # Ensure lv_harness is in PYTHONPATH
    lv_harness_root = str(Path(__file__).resolve().parent)
    if lv_harness_root not in sys.path:
        sys.path.insert(0, lv_harness_root)

    from lv_harness.orchestrator import HarnessOrchestrator

    class BatchEvolutionOrchestrator(HarnessOrchestrator):
        """Orchestrator dedicated to offline batch runs.

        Semantics:
        1. After answering each question, still capture the learning and write back the downstream result of the injected skill.
        2. Do not promote skills after each question.
        3. Promote skills uniformly after each batch ends; learnings that have not reached the threshold are kept for subsequent batches.
        """

        class _WorkerDatasetProxy:
            """In-thread QA dataset proxy that provides only mark_answered, to avoid sharing the main dataset state."""

            def mark_answered(self, question_id: str) -> None:
                return

        class _LearningSnapshot:
            """In-thread read-only learning snapshot, to avoid workers writing LearningCapture files."""

            def __init__(self, learnings):
                self._all_learnings = learnings

            @property
            def all_learnings(self):
                return self._all_learnings

        def run_batch(self, batch_size: int = 64):
            """Batch processing mode: multi-threaded reasoning within a batch, with the main thread committing state changes uniformly."""
            self.hooks.trigger("on_harness_start", config=self.config)

            output_path = self._get_output_path()
            done_ids = self._load_done_ids(output_path)

            all_questions = [q for q in self.qa_dataset.questions
                             if q.question_id not in done_ids]

            workers = self._get_worker_count()
            logger.info(f"{len(all_questions)} questions to process in total ({len(done_ids)} skipped)")
            logger.info(
                f"[Concurrency] Offline batch mode enables sample-level multi-threading: "
                f"workers={workers}, batch_size={batch_size}"
            )
            if self._evolution_enabled:
                logger.info(
                    "[Self-evolution] Using batch-level skill promotion: "
                    "workers read skill/experience snapshots read-only, while the main thread captures learnings and distills skills after each batch ends"
                )

            batches = [all_questions[i:i+batch_size]
                       for i in range(0, len(all_questions), batch_size)]

            with open(output_path, "a", encoding="utf-8") as f_out:
                for batch_idx, batch in enumerate(batches):
                    if not batch:
                        continue
                    logger.info(
                        f"Processing batch {batch_idx+1}/{len(batches)} "
                        f"({len(batch)} questions, workers={min(workers, len(batch))})"
                    )

                    evolution_snapshot = self._make_evolution_snapshot(batch)
                    if workers <= 1 or len(batch) == 1:
                        for q in batch:
                            clip_id_for_q = q.before_clip if q.before_clip is not None else -1
                            worker_result = self._process_question_isolated(
                                q, clip_id_for_q, evolution_snapshot
                            )
                            self._commit_worker_result(worker_result, f_out, done_ids)
                    else:
                        max_workers = min(workers, len(batch))
                        ordered_futures = []
                        with ThreadPoolExecutor(max_workers=max_workers) as executor:
                            for q in batch:
                                clip_id_for_q = q.before_clip if q.before_clip is not None else -1
                                future = executor.submit(
                                    self._process_question_isolated,
                                    q,
                                    clip_id_for_q,
                                    evolution_snapshot,
                                )
                                ordered_futures.append((q, clip_id_for_q, future))

                            for future in as_completed([item[2] for item in ordered_futures]):
                                q, _clip_id_for_q = next(
                                    (item[0], item[1])
                                    for item in ordered_futures
                                    if item[2] is future
                                )
                                logger.debug(f"[Concurrency] Question {q.question_id} worker finished")

                        for q, clip_id_for_q, future in ordered_futures:
                            try:
                                worker_result = future.result()
                            except Exception as exc:
                                logger.exception(
                                    f"[Concurrency] Question {q.question_id} worker raised an exception, recording an empty answer: {exc}"
                                )
                                worker_result = self._build_failed_worker_result(
                                    q, clip_id_for_q, exc
                                )
                            self._commit_worker_result(worker_result, f_out, done_ids)

                    self.hooks.trigger("on_batch_complete", batch_idx=batch_idx)

                    self._promote_skills_after_batch(batch_idx=batch_idx)

                    # Incremental reflection: placed after batch-level promote so reflection can see the new skills.
                    self._run_incremental_reflection(batch_idx=batch_idx)

            results = self.evaluator.compute_all()

            # Do the final WISDOM.md distillation after the whole run finishes.
            self._run_post_batch_evolution(results)

            self.hooks.trigger("on_harness_end", results=results)
            self._save_results(results)
            return results

        def _get_worker_count(self) -> int:
            """Read and normalize reasoning.workers."""
            try:
                workers = int(self.config.get("reasoning", {}).get("workers", 1) or 1)
            except Exception:
                workers = 1
            return max(1, workers)

        def _make_evolution_snapshot(self, batch) -> dict:
            """Create a read-only self-evolution snapshot for a batch, so workers do not directly hold the main-thread components."""
            snapshot = {
                "enabled": bool(self._evolution_enabled),
                "learnings": [],
                "skill_router": None,
                "decompose_guidance_by_qid": {},
            }
            if not self._evolution_enabled:
                return snapshot

            learnings = []
            if self._learning_capture:
                learnings = copy.deepcopy(list(self._learning_capture.all_learnings))
                snapshot["learnings"] = learnings

            if self._skill_router:
                snapshot["skill_router"] = copy.deepcopy(self._skill_router)

            if self._wisdom_distiller:
                for q in batch:
                    try:
                        guidance = self._wisdom_distiller.generate_decompose_guidance(
                            learnings,
                            question=q,
                        )
                    except Exception as exc:
                        logger.warning(
                            f"[self-evolution] precomputing decomposition guidance failed, question {q.question_id}: {exc}"
                        )
                        guidance = ""
                    if guidance:
                        snapshot["decompose_guidance_by_qid"][q.question_id] = guidance
            return snapshot

        def _build_isolated_hooks(self):
            """Build independent hooks for each worker, to avoid sharing verification-hook counters across threads."""
            from lv_harness.hooks import HookSystem
            from lv_harness.reasoning.verification_hooks import (
                AnswerVerificationHook,
                SearchResultVerificationHook,
            )

            hooks = HookSystem()
            hooks.register_hook_object(AnswerVerificationHook())
            hooks.register_hook_object(SearchResultVerificationHook())
            return hooks

        def _build_worker_orchestrator(self, evolution_snapshot: dict):
            """Build an in-thread isolated orchestrator."""
            worker = self.__class__.__new__(self.__class__)
            worker.config = copy.deepcopy(self.config)
            worker.config.setdefault("memory", {})["memory_cache_dir"] = ""
            worker.qa_dataset = self._WorkerDatasetProxy()
            worker.memory = worker._build_memory()
            worker.snapshot_mgr = None
            worker.agent = worker._build_agent()
            worker.answer_policy = worker._build_answer_policy()
            worker.evaluator = worker._build_evaluator()
            worker.hooks = self._build_isolated_hooks()
            worker.deferred_questions = []
            worker._output_dir = self._output_dir
            worker._save_trajectory = False
            worker._trajectory_dir = None
            worker._evolution_enabled = bool(evolution_snapshot.get("enabled", False))
            worker._learning_capture = None
            worker._skill_promoter = None
            worker._skill_router = None
            worker._wisdom_distiller = None
            worker._current_injected_skill_id = None
            worker._decompose_guidance_by_qid = copy.deepcopy(
                evolution_snapshot.get("decompose_guidance_by_qid", {})
            )

            if worker._evolution_enabled:
                worker._learning_capture = self._LearningSnapshot(
                    copy.deepcopy(evolution_snapshot.get("learnings", []))
                )
                skill_router_snapshot = evolution_snapshot.get("skill_router")
                if skill_router_snapshot is not None:
                    worker._skill_router = copy.deepcopy(skill_router_snapshot)

            return worker

        def _inject_skill_for_question(self, q):
            """Read-only skill injection inside a worker. The decomposition guidance comes from the main thread's precomputed snapshot."""
            if hasattr(self.agent, "set_decompose_guidance"):
                guidance = getattr(self, "_decompose_guidance_by_qid", {}).get(
                    q.question_id,
                    "",
                )
                try:
                    self.agent.set_decompose_guidance(guidance)
                except Exception as exc:
                    logger.warning(f"[self-evolution] worker failed to set decomposition guidance: {exc}")

            return super()._inject_skill_for_question(q)

        def _handle_question_without_evolution(self, q, clip_id: int):
            """Process a single question within a thread. Only does injection, reasoning, and evaluation, without writing self-evolution state."""
            from lv_harness.data.types import AgentAnswer

            self.hooks.trigger("on_question_received", question=q, clip_id=clip_id)

            if self._evolution_enabled:
                self._inject_skill_for_question(q)

            try:
                answer = self.agent.answer(q, self.memory)
                self.hooks.trigger("on_answer_generated", answer=answer, question=q)

                if self.answer_policy.should_answer(answer, clip_id, q):
                    record = self._record_answer(q, answer, clip_id)
                    return (record, answer)

                self.deferred_questions.append((q, clip_id))
                return None
            except Exception as e:
                logger.error(f"Failed to process question {q.question_id}: {e}")
                try:
                    logger.info(f"[SelfHeal] retrying question {q.question_id}")
                    answer = self.agent.answer(q, self.memory)
                    self.hooks.trigger("on_answer_generated", answer=answer, question=q)
                    record = self._record_answer(q, answer, clip_id)
                    return (record, answer)
                except Exception as e2:
                    logger.error(f"[SelfHeal] retry still failed: {e2}")
                    failed_answer = AgentAnswer(content="", confidence=0.0, is_final=True)
                    record = self._record_answer(q, failed_answer, clip_id)
                    return (record, failed_answer)

        def _process_question_isolated(self, q, clip_id: int, evolution_snapshot: dict) -> dict:
            """Process a single question in an isolated worker state, returning a result that the main thread can commit."""
            worker = self._build_worker_orchestrator(evolution_snapshot)
            injected_skill_id = None
            fired_skill_ids = []
            try:
                worker.memory.on_video_start(q.video_name, mem_path=q.mem_path)
                result = worker._handle_question_without_evolution(q, clip_id)
                injected_skill_id = getattr(worker, "_current_injected_skill_id", None)
                fired_skill_ids = list(getattr(worker, "_current_fired_skill_ids", []) or [])
                if not result:
                    return {
                        "question": q,
                        "clip_id": clip_id,
                        "record": None,
                        "answer": None,
                        "injected_skill_id": injected_skill_id,
                        "fired_skill_ids": fired_skill_ids,
                    }
                record, answer = result
                return {
                    "question": q,
                    "clip_id": clip_id,
                    "record": record,
                    "answer": answer,
                    "injected_skill_id": injected_skill_id,
                    "fired_skill_ids": fired_skill_ids,
                }
            finally:
                try:
                    worker.memory.on_video_end(q.video_name)
                except Exception:
                    pass

        def _build_failed_worker_result(self, q, clip_id: int, exc: Exception) -> dict:
            """Build a failure record when worker initialization or execution hits an uncaught exception."""
            from lv_harness.data.types import AgentAnswer

            failed_answer = AgentAnswer(content="", confidence=0.0, is_final=True)
            evaluator = self._build_evaluator()
            record = evaluator.record(q, failed_answer, clip_id, {})
            return {
                "question": q,
                "clip_id": clip_id,
                "record": record,
                "answer": failed_answer,
                "injected_skill_id": None,
                "fired_skill_ids": [],
                "error": str(exc),
            }

        def _commit_worker_result(self, worker_result: dict, f_out, done_ids: set) -> None:
            """The main thread serially commits worker results, uniformly writing the evaluator, the file, and the self-evolution state."""
            q = worker_result.get("question")
            record = worker_result.get("record")
            answer = worker_result.get("answer")
            if not q or not record or not answer:
                return

            self.evaluator.records.append(record)
            self.qa_dataset.mark_answered(q.question_id)
            self.hooks.trigger("on_answer_evaluated", record=record, question=q, answer=answer)

            result_obj = self._build_result_obj(q, record, answer)
            f_out.write(json.dumps(result_obj, ensure_ascii=False) + "\n")
            f_out.flush()
            done_ids.add(q.question_id)

            if self._evolution_enabled:
                try:
                    self._evolve_after_answer(
                        q,
                        answer,
                        record,
                        worker_result.get("clip_id", -1),
                        injected_skill_id=worker_result.get("injected_skill_id"),
                        fired_skill_ids=worker_result.get("fired_skill_ids", []),
                        mark_skill_injected=True,
                        memory_stats=record.memory_stats,
                    )
                except Exception as exc:
                    logger.warning(
                        f"[self-evolution] main thread failed to submit learning, question {q.question_id}: {exc}"
                    )


        def _evolve_after_answer(
            self,
            q,
            answer,
            record,
            clip_id,
            injected_skill_id=None,
            fired_skill_ids=None,
            mark_skill_injected: bool = False,
            memory_stats=None,
        ):
            """After answering, only capture experience; do not promote a skill at the end of a single question."""
            if not self._learning_capture:
                return

            skill_ids = []
            skill_id = injected_skill_id or getattr(self, "_current_injected_skill_id", None)
            if skill_id:
                skill_ids.append(skill_id)
            for fired_skill_id in fired_skill_ids or []:
                if fired_skill_id not in skill_ids:
                    skill_ids.append(fired_skill_id)

            if skill_ids and self._skill_router:
                fired_set = set(fired_skill_ids or [])
                for sid in skill_ids:
                    if mark_skill_injected and (sid == skill_id or sid in fired_set):
                        self._skill_router.mark_injected(sid)
                    self._skill_router.record_outcome(sid, record.is_correct)
                    logger.debug(
                        f"[self-evolution] downstream write-back: skill={sid} "
                        f"is_correct={record.is_correct}"
                    )
                if skill_id == getattr(self, "_current_injected_skill_id", None):
                    self._current_injected_skill_id = None
                self._current_fired_skill_ids = []

            if memory_stats is None:
                memory_stats = record.memory_stats or {}
            learning = self._learning_capture.capture_from_eval(
                question=q,
                answer=answer,
                is_correct=record.is_correct,
                memory_stats=memory_stats,
                clip_id=clip_id,
            )

            if learning:
                self.hooks.trigger(
                    "on_learning_captured",
                    learning=learning,
                    question=q,
                )

            ledger_snapshot = None
            if answer.reasoning_trace:
                for item in answer.reasoning_trace:
                    if isinstance(item, dict) and "_ledger_snapshot" in item:
                        ledger_snapshot = item["_ledger_snapshot"]
                        break
            if ledger_snapshot:
                try:
                    ledger_learnings = self._learning_capture.capture_from_ledger(
                        question=q,
                        answer=answer,
                        is_correct=record.is_correct,
                        ledger_snapshot=ledger_snapshot,
                        memory_stats=memory_stats,
                    )
                    for ll in ledger_learnings:
                        self.hooks.trigger(
                            "on_learning_captured",
                            learning=ll,
                            question=q,
                        )
                except Exception as exc:
                    logger.warning(f"[Self-evolution] capture_from_ledger raised an exception: {exc}")


        def _promote_skills_after_batch(self, batch_idx: int) -> None:
            """Uniformly promote skills after each batch ends."""
            if not self._evolution_enabled:
                return
            if not self._learning_capture or not self._skill_promoter:
                return

            all_learnings = self._learning_capture.all_learnings
            if not all_learnings:
                logger.info(f"[Self-evolution] batch {batch_idx+1}: no experience records, skipping skill distillation")
                return

            threshold = getattr(self._skill_promoter, "promote_threshold", "N/A")
            new_skills = self._skill_promoter.maybe_promote(all_learnings)
            unpromoted_count = sum(
                1 for learning in all_learnings
                if not getattr(learning, "promoted", False)
            )

            if not new_skills:
                logger.info(
                    f"[Self-evolution] batch {batch_idx+1}: no new skills produced "
                    f"(promote_threshold={threshold}, unpromoted experiences={unpromoted_count})"
                )
                return

            for skill in new_skills:
                if self._skill_router:
                    self._skill_router.register_skill(skill)
                self.hooks.trigger("on_skill_promoted", skill=skill)
                logger.info(
                    f"[Self-evolution] batch {batch_idx+1} new skill distilled: {skill.name} "
                    f"(success_rate={skill.success_rate:.0%}, "
                    f"from {len(skill.created_from)} learnings)"
                )

            logger.info(
                f"[Self-evolution] batch {batch_idx+1}: skill distillation complete | "
                f"new/updated skills: {len(new_skills)} | "
                f"unpromoted experiences: {unpromoted_count}"
            )

    # Build the output directory
    n_suffix = "all" if args.num_questions == -1 else f"n{args.num_questions}"
    # Toggle tags: visual layer kfon/kfoff, self-evolution evoon/evooff
    kf_tag = "kfon" if getattr(args, "visual_layer_enabled", False) else "kfoff"
    evo_tag = "evoon" if getattr(args, "evolution", False) else "evooff"
    output_dir = args.output_dir or os.path.join(
        lv_harness_root, "data", "results",
        f"lvomnibench_{n_suffix}_{kf_tag}_{evo_tag}_{args.model}_{time.strftime('%Y%m%d_%H%M%S')}"
    )
    os.makedirs(output_dir, exist_ok=True)

    # Build override parameters
    # Auto-fix the eventgraph_dir path
    eventgraph_dir = resolve_path(args.eventgraph_dir)
    api_config = resolve_path(args.api_config)
    memory_config = resolve_path(args.memory_config)

    # Decide temporal_mode based on the run mode
    is_streaming = getattr(args, 'streaming', False)
    temporal_mode = "periodic" if is_streaming else "end_of_video"

    # Task name: derive from the subset_path filename first, so that different datasets such as m3bench/lvomnibench
    # produce output files matching the directory name (e.g. m3bench_robot_all-<model>-lv_harness.jsonl)
    task_suffix = "all" if args.num_questions == -1 else f"subset_{args.num_questions}"
    try:
        task_name = os.path.splitext(os.path.basename(subset_path))[0] or f"lvomnibench_{task_suffix}"
    except Exception:
        task_name = f"lvomnibench_{task_suffix}"

    overrides = {
        # Data
        "task": task_name,
        "data.annotation_file": subset_path,
        "data.temporal_mode": temporal_mode,
        # Memory
        "memory.strategy": args.strategy,
        "memory.eventgraph_dir": eventgraph_dir,
        "memory.memory_config_path": memory_config,
        # Reasoning
        "reasoning.agent": getattr(args, "agent", "ledger_multi_round"),
        "reasoning.backend": args.backend,
        "reasoning.model": args.model,
        "reasoning.max_rounds": args.max_rounds,
        "reasoning.workers": args.workers,
        "reasoning.temperature": args.temperature,
        "reasoning.seed": args.seed if args.seed >= 0 else None,
        "reasoning.api_config_path": api_config,
        # Evaluation
        "evaluation.eval_model": args.eval_model,
        "evaluation.string_match_first": args.string_match_first,
        "evaluation.metrics": ["accuracy", "accuracy_by_category", "answer_latency"],
        # Output
        "output.dir": output_dir,
        "output.save_trajectory": getattr(args, 'save_trajectory', False),
    }

    # TaskLedger-specific parameters (injected only for ledger-family agents)
    if getattr(args, "agent", "ledger_multi_round") in (
        "ledger_multi_round",
    ):
        overrides["reasoning.ledger.enabled"] = True
        overrides["reasoning.ledger.planner.enabled"] = True
        overrides["reasoning.ledger.planner.max_subtasks"] = int(
            getattr(args, "ledger_max_subtasks", 5)
        )
        overrides["reasoning.ledger.planner.temperature"] = float(
            getattr(args, "planner_temperature", 0.2)
        )
        overrides["reasoning.ledger.scheduler.max_attempts_per_subtask"] = int(
            getattr(args, "ledger_max_attempts", 3)
        )
        # By default synthesis uses the ledger only; with --ledger_synthesis_raw it also attaches raw retrieval
        overrides["reasoning.ledger.synthesis.use_ledger_only"] = (
            not bool(getattr(args, "ledger_synthesis_raw", False))
        )

    # DecomposeOnly-specific parameters (injected only when agent == decompose_only)
    # Reuses the same reasoning.ledger.* config path; DecomposeOnlyMultiRoundAgent
    # only reads the planner / scheduler subconfig in __init__, not synthesis / progress.
    if getattr(args, "agent", "ledger_multi_round") == "decompose_only":
        overrides["reasoning.ledger.enabled"] = True
        overrides["reasoning.ledger.planner.enabled"] = True
        overrides["reasoning.ledger.planner.max_subtasks"] = int(
            getattr(args, "ledger_max_subtasks", 5)
        )
        overrides["reasoning.ledger.planner.temperature"] = float(
            getattr(args, "planner_temperature", 0.2)
        )
        overrides["reasoning.ledger.scheduler.max_attempts_per_subtask"] = int(
            getattr(args, "ledger_max_attempts", 3)
        )

    # Streaming-mode-specific config
    if is_streaming:
        if args.clip_dir_template:
            overrides["data.clip_dir_template"] = args.clip_dir_template
        overrides["memory.eventgraph_incremental"] = getattr(
            args, 'eventgraph_incremental', False
        )
        overrides["memory.eventgraph_update_interval"] = getattr(
            args, 'eventgraph_update_interval', 20
        )
        overrides["memory.eventgraph_model"] = getattr(
            args, 'eventgraph_model', 'DeepSeek-V3.1T'
        )
        # Memory cache directory
        memory_cache_dir = getattr(args, 'memory_cache_dir', '')
        if memory_cache_dir:
            overrides["memory.memory_cache_dir"] = memory_cache_dir

    if args.evolution:
        overrides["evolution.enabled"] = True
        # Read-only mode
        if getattr(args, "evolution_readonly", False):
            overrides["evolution.readonly"] = True
        # Determine evolution_dir: prefer the user-specified one, otherwise place under output_dir to keep each experiment isolated
        evo_dir = args.evolution_dir or os.path.join(output_dir, ".lv_harness")
        overrides["evolution.dir"] = evo_dir
        overrides["evolution.learnings_dir"] = f"{evo_dir}/learnings"
        overrides["evolution.skills_dir"] = f"{evo_dir}/skills"
        overrides["evolution.wisdom_path"] = f"{evo_dir}/WISDOM.md"
        overrides["evolution.reflections_dir"] = f"{evo_dir}/reflections"
        overrides["evolution.load_prior_skills"] = args.load_prior_skills
        overrides["evolution.load_prior_learnings"] = args.load_prior_learnings
        overrides["evolution.promote_threshold"] = args.promote_threshold
        overrides["evolution.route_threshold"] = args.route_threshold
        overrides["evolution.visual_layer_enabled"] = bool(
            getattr(args, "visual_layer_enabled", False)
        )
        overrides["evolution.wisdom_use_llm"] = args.wisdom_use_llm
        overrides["evolution.wisdom_llm_model"] = args.wisdom_model
        overrides["evolution.reflection_llm_max_tokens"] = args.reflection_llm_max_tokens
        # P1: toggle for LLM generation of Skill special_instructions
        if getattr(args, "skill_use_llm_instructions", False):
            overrides["evolution.skill_use_llm_instructions"] = True
        if getattr(args, "skill_instructions_llm_model", None):
            overrides["evolution.skill_instructions_llm_model"] = args.skill_instructions_llm_model

    # DeepSeek-V4 thinking mode toggle
    if getattr(args, "enable_thinking", False):
        overrides["reasoning.enable_thinking"] = True
        overrides["evaluation.enable_thinking"] = True

    # Reason output mode toggle (on by default, off with --no_reason)
    if getattr(args, "no_reason", False):
        overrides["reasoning.enable_reason"] = False

    # Third layer: visual layer parameters (off by default. When on, project the config into memory.visual_layer.*)
    if getattr(args, "visual_layer_enabled", False):
        overrides["memory.visual_layer.enabled"] = True
        overrides["memory.visual_layer.clips_root"] = getattr(args, "visual_clips_root", "") or ""
        overrides["memory.visual_layer.keyframe_dir_name"] = getattr(
            args, "visual_keyframe_dir_name", "keyframe_hybridv2"
        )
        overrides["memory.visual_layer.max_images_per_call"] = int(
            getattr(args, "visual_max_images_per_call", 5) or 5
        )

    logger.info("=" * 60)
    logger.info("LVOmniBench subset evaluation")
    logger.info("=" * 60)
    logger.info(f"  Dataset: {subset_path}")
    logger.info(f"  Number of questions: {args.num_questions}")
    logger.info(f"  Model: {args.model}")
    logger.info(f"  Memory strategy: {args.strategy}")
    logger.info(f"  Reasoning Agent: {getattr(args, 'agent', 'multi_round_search')}")
    logger.info(f"  Run mode: {'streaming reasoning' if is_streaming else 'offline batch'}")
    logger.info(f"  EventGraph: {args.eventgraph_dir}")
    if is_streaming:
        logger.info(f"  Clip directory template: {getattr(args, 'clip_dir_template', 'N/A')}")
        logger.info(f"  EventGraph incremental update: {getattr(args, 'eventgraph_incremental', False)}")
        memory_cache_dir = getattr(args, 'memory_cache_dir', '')
        if memory_cache_dir:
            logger.info(f"  Memory cache directory: {memory_cache_dir}")
        else:
            logger.info(f"  Memory cache: not enabled")
    if args.evolution:
        evo_dir = args.evolution_dir or os.path.join(output_dir, ".lv_harness")
        logger.info(f"  Self-evolution: enabled")
        logger.info(f"    evolution_dir: {evo_dir}")
        logger.info(f"    load_prior_skills: {args.load_prior_skills}")
        logger.info(f"    load_prior_learnings: {args.load_prior_learnings}")
        logger.info(f"    promote_threshold: {args.promote_threshold}")
        logger.info(f"    route_threshold: {args.route_threshold}")
        logger.info(f"    wisdom_use_llm: {args.wisdom_use_llm}")
        logger.info(f"    skill_use_llm_instructions: {getattr(args, 'skill_use_llm_instructions', False)}")
        if getattr(args, "evolution_readonly", False):
            logger.info(f"    [warning] readonly mode: only load skills for injection, do not write any updates")
    logger.info(f"  Max rounds: {args.max_rounds}")
    logger.info(f"  Concurrency: {args.workers}")
    logger.info(f"  string_match_first: {args.string_match_first}")
    logger.info(f"  Output directory: {output_dir}")
    logger.info("=" * 60)

    # Create the Orchestrator and run
    orchestrator_cls = HarnessOrchestrator if is_streaming else BatchEvolutionOrchestrator
    harness = orchestrator_cls(overrides=overrides)
    if is_streaming:
        results = harness.run_streaming()
    else:
        results = harness.run_batch(batch_size=args.batch_size)

    # Print results
    logger.info("=" * 60)
    logger.info("Evaluation complete")
    logger.info("=" * 60)
    for metric, value in results.items():
        if isinstance(value, dict):
            logger.info(f"[{metric}]")
            for k, v in value.items():
                if isinstance(v, float):
                    logger.info(f"  {k}: {v:.4f}")
                else:
                    logger.info(f"  {k}: {v}")
        else:
            logger.info(f"  {metric}: {value}")

    return results


def main():
    args = parse_args()

    # Generate the subset JSON path
    if args.subset_output:
        subset_path = args.subset_output
    else:
        lv_harness_root = str(Path(__file__).resolve().parent)
        subset_dir = os.path.join(lv_harness_root, "data", "annotations")
        os.makedirs(subset_dir, exist_ok=True)
        file_suffix = "all" if args.num_questions == -1 else f"subset_{args.num_questions}"
        # When there is an offset, add an offset marker to the filename to avoid cache conflicts
        if args.question_offset != 0:
            file_suffix += f"_off{args.question_offset}"
        subset_path = os.path.join(subset_dir, f"lvomnibench_{file_suffix}.json")

    # Step 1: take the subset
    if os.path.exists(subset_path):
        logger.info(f"Subset file already exists, skipping generation: {subset_path}")
        with open(subset_path, "r", encoding="utf-8") as f:
            subset = json.load(f)
        total_q = sum(len(v.get("qa_list", [])) for v in subset.values())
        logger.info(f"Existing subset: {len(subset)} videos, {total_q} questions")
    else:
        subset = extract_subset(args.annotation_file, args.num_questions, subset_path,
                                question_offset=args.question_offset)

    if args.dry_run:
        logger.info("Dry run mode: only generate the subset JSON, do not run evaluation")
        return

    # Step 2: run evaluation
    results = run_evaluation(args, subset_path)

    return results


if __name__ == "__main__":
    main()
