"""
evolution/llm_utils.py: lightweight LLM calling utilities, used by SkillPromoter / WisdomDistiller.

Does not depend on mmagent. Uses the openai SDK directly together with lv_harness's own api_config.json.
"""
import json
import logging
import time
from pathlib import Path
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

# Default api_config path (relative to the lv_harness root directory)
_DEFAULT_API_CONFIG = "configs/api_config.json"

# Module-level cache: avoid re-reading json + creating a client on every call
_client_cache: Dict[str, "openai.OpenAI"] = {}


def _resolve_api_config_path(api_config_path: Optional[str] = None) -> str:
    """Resolve the absolute path of api_config.json."""
    if api_config_path and Path(api_config_path).exists():
        return api_config_path
    # Try to infer from the lv_harness package root directory
    pkg_root = Path(__file__).resolve().parent.parent.parent  # lv_harness/
    candidate = pkg_root / _DEFAULT_API_CONFIG
    if candidate.exists():
        return str(candidate)
    # Finally try cwd
    if Path(_DEFAULT_API_CONFIG).exists():
        return _DEFAULT_API_CONFIG
    raise FileNotFoundError(
        f"api_config.json not found: tried {api_config_path}, {candidate}, {_DEFAULT_API_CONFIG}"
    )


def _get_client(model: str, api_config_path: Optional[str] = None):
    """Get or create an OpenAI client (with caching)."""
    import openai

    cache_key = f"{model}::{api_config_path or ''}"
    if cache_key in _client_cache:
        return _client_cache[cache_key]

    config_path = _resolve_api_config_path(api_config_path)
    with open(config_path) as f:
        api_cfg = json.load(f)

    if model not in api_cfg:
        raise KeyError(f"model '{model}' is not configured in {config_path}")

    client = openai.OpenAI(
        base_url=api_cfg[model].get("base_url") or None,
        api_key=api_cfg[model]["api_key"],
    )
    _client_cache[cache_key] = client
    return client


def call_llm(
    model: str,
    prompt: str,
    *,
    system_prompt: str = "",
    api_config_path: Optional[str] = None,
    temperature: float = 0.4,
    max_tokens: int = 2048,
    timeout: int = 60,
    max_retries: int = 5,
    enable_thinking: bool = False,
    json_mode: bool = False,
) -> str:
    """Call the LLM and return the text response.

    Args:
        model: model name (must be configured in api_config.json)
        prompt: user prompt
        system_prompt: optional system prompt
        api_config_path: path to api_config.json (None to infer automatically)
        temperature: sampling temperature
        max_tokens: maximum output tokens
        timeout: per-request timeout (seconds)
        max_retries: maximum number of retries
        enable_thinking: DeepSeek-V4 thinking mode switch (disabled by default)
        json_mode: enable JSON mode, forcing the LLM to output valid JSON (disabled by default)

    Returns:
        the text generated by the LLM

    Raises:
        RuntimeError: all retries failed
    """
    client = _get_client(model, api_config_path)

    messages: List[Dict] = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    # DeepSeek-V4 family: control thinking mode via the enable_thinking parameter (disabled by default)
    extra_kwargs = {}
    if "deepseek-v4" in model.lower():
        extra_kwargs["extra_body"] = {"enable_thinking": enable_thinking}

    # JSON mode: force the LLM to output valid JSON, eliminating formatting issues such as code fences / prefix text at the decoding level
    if json_mode:
        extra_kwargs["response_format"] = {"type": "json_object"}

    for retry in range(max_retries):
        try:
            resp = client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                top_p=0.95,
                timeout=timeout,
                **extra_kwargs,
            )
            text = resp.choices[0].message.content or ""
            return text.strip()
        except Exception as e:
            sleep_s = min(20, 2 * (retry + 1))
            logger.warning(
                f"[llm_utils] LLM call failed (retry {retry + 1}/{max_retries}): {e}"
            )
            time.sleep(sleep_s)

    raise RuntimeError(f"LLM call failed (after {max_retries} retries): model={model}")
