"""
Skill data type definitions.
"""
from dataclasses import dataclass, field
from typing import List, Optional, Dict
import numpy as np


@dataclass
class InstructionSlot:
    """An instruction slot inside a Skill, dispatched by cognitive pattern.

    A single Skill may contain multiple InstructionSlots, each corresponding to a
    cognitive pattern (such as counting, spatial_location). During routing only the
    matching slot is injected.
    """
    slot_id: str  # e.g. "counting", "spatial_location"
    pattern_keywords: List[str] = field(default_factory=list)  # cognitive pattern keywords
    context_keywords: List[str] = field(default_factory=list)  # transferable context keywords
    instructions: str = ""  # instructions specific to this slot
    hit_count: int = 0  # number of times routed to this slot
    success_count: int = 0  # number of correct answers after a hit


@dataclass
class Skill:
    """A reusable reasoning skill."""
    skill_id: str
    name: str
    description: str

    # Trigger conditions
    trigger_conditions: List[str] = field(default_factory=list)
    trigger_embedding: Optional[np.ndarray] = None

    # Question type (aligned with question_type in LearningCapture, used for precise routing)
    question_type: str = "general"

    # Execution strategy
    # recommended_search_strategy:
    #   - For positive-sample clusters (hard_win / search_win / error_correction):
    #     record the most common query prefix pattern (`event_first` / `video_drilldown` /
    #     `neighbor`) in the cluster's historical trajectories, used only as an internal
    #     statistics field.
    #   - For negative-sample clusters (calibration / search_fail): set to empty string "",
    #     because the query prefix distribution of failure paths should not be used as a
    #     downstream recommendation.
    #   Note: since v2 this field is no longer injected separately into the system prompt.
    #   Strategy guidance is uniformly expressed through if-then rules in
    #   special_instructions, which has higher information density.
    recommended_search_strategy: str = "event_first"
    recommended_prompt_template: Optional[str] = None
    recommended_max_rounds: int = 10
    special_instructions: str = ""
    # P1 fix: the source of special_instructions. Used to decide whether it should be
    # regenerated by the LLM at the next update, instead of relying on a text marker
    # like .startswith("[template]") that would pollute the prompt.
    #   - "template": produced via the _template_instructions fallback
    #   - "llm":      produced successfully via _generate_special_instructions
    #   - "custom":   externally specified / manually edited
    instructions_source: str = "template"

    # Sub-skill routing: within a single Skill, dispatch to different instruction slots
    # by cognitive pattern. If instruction_slots is non-empty, routing first matches a
    # slot and injects only that slot's instructions. If no slot matches, fall back to
    # special_instructions.
    instruction_slots: List[InstructionSlot] = field(default_factory=list)

    # Evolution metadata
    version: int = 1
    created_from: List[str] = field(default_factory=list)
    # Note:
    #   success_count/failure_count/success_rate represent the correct/incorrect rate of
    #   the batch of Learning samples that produced this Skill. Semantically they only
    #   reflect "source signal quality" (e.g. error-question clusters are always 0).
    #   The truly meaningful guidance comes from the downstream_* metrics below: the
    #   correct/incorrect counts of new questions after the Skill is injected into them
    #   by the SkillRouter.
    success_count: int = 0
    failure_count: int = 0
    success_rate: float = 0.0

    # Downstream metrics: future win rate after the Skill is actually used (injected)
    usage_count: int = 0
    downstream_success: int = 0
    downstream_failure: int = 0
    downstream_success_rate: float = 0.0

    last_updated: str = ""

    # Examples (few-shot)
    examples: List[Dict] = field(default_factory=list)
